apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://forgejo.aiectomy.xyz/pbourke/movieswipe.git//deploy/kustomize/base?ref=main
  - httproute.yaml
  - vpa.yaml
  - secret-api-keys.yaml
images:
  - name: ghcr.io/brk3/movieswipe
    newName: forgejo.aiectomy.xyz/pbourke/movieswipe
    newTag: v0.1.2 # {"$imagepolicy": "flux-system:movieswipe:tag"}
    digest: sha256:3b0499472588b43c8a057e46e1d9ec51c9930d9a8c3974ac01a4f45a721c25e6 # {"$imagepolicy": "flux-system:movieswipe:digest"}
