apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://forgejo.aiectomy.xyz/pbourke/movieswipe.git//deploy/kustomize/base?ref=main
  - httproute.yaml
  - vpa.yaml
  - secret-api-keys.yaml
images:
  - name: ghcr.io/brk3/movieswipe
    newName: forgejo.aiectomy.xyz/pbourke/movieswipe
    newTag: v0.1.1 # {"$imagepolicy": "flux-system:movieswipe:tag"}
    digest: sha256:04a065481444ddb87314ad6a5665406db4a1c4f12149781d32a9677b715d6a01 # {"$imagepolicy": "flux-system:movieswipe:digest"}
