apiVersion: v1
kind: Secret
metadata:
    name: movieswipe-api-keys
    namespace: movieswipe
type: Opaque
stringData:
    TMDB_TOKEN: ENC[AES256_GCM,data:uEUsO52raHLB3QcFKoClIvIacpL/Dxy0c/RxklzE+rYTjfM9545NUYjgXgV64H2OzReHv/OOhdnFWjIQY/itcQaM4rOP0yNX9dn505u/YDVnucfzZxlHL/vKoXzKoOXezm+jVIuPTebapfc+21Lv0eu/8MUXHSRKhjZf/Xr99lh7/XClDrL9XUukFm8qEdKTu5rgHPH+fjUyIHmVbGGyZhO8KiDl4I5/OZDLIMy1ivoa6eCMWeHf0bLuRgEUJpzXvkEsEdXvgAp7FU/Gu1gmcok40Yp4jIfmT2qFmb8AKUJaUeUFORC0m07C8OQBzDk=,iv:Zf6nTeTXcl8CI2qMzRQ4ceCzR87gDFUTTNp5uaJOlCA=,tag:xLG/ao9zdiLbLWBtD+CHsA==,type:str]
    OMDB_API_KEY: ENC[AES256_GCM,data:m0gNRpQn3bg=,iv:bED5Rrz1vceFJ395/75eavqCpfHIAVzZRE0iGO+3HCg=,tag:KrFSeArs8LpUNQrANaMJbA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPUGNScHlHQUNWMFhFY2JY
            WkRaQmdnQ1JUVEtJMlRDUmRWTDU2SzRQbUgwCm0zSW8xcTBKWmpEK2FxRDFQWnNE
            T0dEakZMRGcvZXNYSFVFNkNhNXFDWU0KLS0tIFFpKzRsbDRhcDdBc2grZXRwZkVv
            TTN2V2tLc21TN1MrTGFRb1k4V2ljM00KkywASTMtVX1PIZwwi0MbBTiTUlLl3fUr
            H+y+lfJ7DRm/WDzaxaGvQ7GidnrQLJXz34fBQlLCedhMHgkn/DsM1Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14k8hl446lvn93q8mqam94fl46c5r6xzu7fcu0dq3763vp2wrze5slp2fkg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-15T17:05:52Z"
    mac: ENC[AES256_GCM,data:WIwg6XwIpbeJRiL1uQHWiH/ZWCFoOkfIDDMXE/buFeTV/FNrrDgpnnrP6DdirBFx9RWS5bfGHHkYMDj9qj/YaKiRVFGc3AbqyTrvLEweOTaWrt9t2njqxDe7gWNLhp72QzrQ7MC54kL4tnPRxesnAZDbeMipidFXNmMNxkNhaXQ=,iv:d2XHeqGQR5JdyAreYGgFP0Wr3NBjy73FnokOMqRcFMA=,tag:wcRGy8kgc/2hQsHpwzHWUw==,type:str]
    version: 3.13.3
