apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: forgejo
  namespace: forgejo
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: forgejo
  updatePolicy:
    updateMode: "InPlaceOrRecreate"
  resourcePolicy:
    containerPolicies:
      - containerName: forgejo
        maxAllowed:
          memory: 1500Mi
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: forgejo-runner
  namespace: forgejo
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: forgejo-runner
  updatePolicy:
    updateMode: "InPlaceOrRecreate"
  resourcePolicy:
    containerPolicies:
      - containerName: runner
        maxAllowed:
          memory: 512Mi
      - containerName: dind
        maxAllowed:
          memory: 2Gi
