apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-clusterissuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: paul.bourke@pm.me
    privateKeySecretRef:
      name: letsencrypt-clusterissuer-key
    solvers:
    - http01:
        ingress:
          class: traefik
