- greeting:
    text_size: xl
    text: Dagda

- datetime:
    text_size: xl
    format:
      dateStyle: medium
      timeStyle: short
      hourCycle: h23

- kubernetes:
    cluster:
      show: true
      cpu: true
      memory: true
      showLabel: true
      label: dagda
    nodes:
      show: false

- openmeteo:
    label: Dublin
    latitude: 53.3498
    longitude: -6.2603
    units: metric
    cache: 15

- search:
    provider: duckduckgo
    target: _blank
