apiVersion: v1
kind: Service
metadata:
  name: prometheus-nodeport
  namespace: monitoring
  labels:
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/instance: k8s
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 2.48.1
spec:
  type: NodePort
  selector:
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/instance: k8s
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: kube-prometheus
  ports:
    - name: web
      port: 9090
      protocol: TCP
      targetPort: web
      #nodePort: 30000 # Optional: Specify a port or leave it out for Kubernetes to assign one.
      #- name: reloader-web
      #port: 8080
      #protocol: TCP
      #targetPort: reloader-web
      #nodePort: 30001 # Optional: Specify a port or leave it out for Kubernetes to assign one.
