apiVersion: v1
kind: Secret
metadata:
    name: kured-secret
    namespace: kured
type: Opaque
stringData:
    notify-url: ENC[AES256_GCM,data:8LcJ3nGYSZr6OgmQ2CYZb5u2PtYFe/X9cehRjiK7RovbEAFl3useJQS703a91GPjg+ehUmQFvDQISjUfZkmakG4SuX8yFCqNVxwmCEp8OKIIcw3Ny4M=,iv:Fx/f9tDnAwvHAknaKYwQ33ZVZXbB5j14ViQCWBEkyVU=,tag:5SgD3LsoslnvKmBYpOYo/g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQVW1sWkl1YUtBaUhWeVJ2
            SGpzT1N1NEFVd2RoTzM5aUUwbFBIa2w4OEFVCkxsWnFCVjVDYitoNWNJL29ma2Nw
            WFZVVFdJZkhpZnZPa3dBbU9uaWhaYmsKLS0tIGc5VWtwc0tEWmx0cEZ1cWhEQ1c3
            RXZobWUxd25uNVE0anowMDdaKzJwdFEKbBpAbLO1r6NgptcZqWlDFECfvn7d7/9m
            iXtJtAUuvS50jJp7OL7VzP2MoykK2ANHUr92ykgJIBEJqR4tH0TH0w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14k8hl446lvn93q8mqam94fl46c5r6xzu7fcu0dq3763vp2wrze5slp2fkg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-18T11:57:09Z"
    mac: ENC[AES256_GCM,data:hkMq8CkbvJBGWrtsuUEB2/qt1Vvn5voDoNUpPXdLKMUy6MbOD3zQssEkH2eRiDtI7lRuhC61nuFP4Ua/2HHdjRbfxbRDlmLtol46QfYEo0xq/0rlsayMNtLeDPYioEOJVkzlVXlOgPYru8LX2IgajwGW6whlnmEiv1QEipTvLlE=,iv:OLjWRfxLBpsZxvZx2Bnfid2oK0a1zwiyxVtKGETS/jM=,tag:CH7fe+kT60iZLy20JuhmcA==,type:str]
    version: 3.13.3
