apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: kured
  namespace: kured
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kured
      app.kubernetes.io/instance: kured-kured
  endpoints:
    - port: metrics
      path: /metrics
      interval: 60s
