apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-aiectomy-xyz
  namespace: envoy-gateway-system
spec:
  secretName: wildcard-aiectomy-xyz-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "*.aiectomy.xyz"
    - "aiectomy.xyz"
