apiVersion: v1
kind: Secret
metadata:
    name: flux-telegram-token
    namespace: flux-system
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:T9ObiYQ/GOM6VpPjYV8wAwc8NiQBIVzHYgfrGWzyHPvVqHCJN723hh2WT2BTOQ==,iv:HfXefrKZI8zjuvNcbexbbmFzKPvIyHC4VQhXFRRGaH8=,tag:/ZwIQGyHBp5PIfmfOWptRg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBN2FFQ2E1WHVqdmlGb2Nz
            aHRrdEJsMzRMQUdMU1FlRzB1M2RiV3NWM1Y4CkRoRXlaS1QycHhxSGtYYndZSWpQ
            MnJqdE9Ib2s4dlNKQ3QvRGo3dzBxSVkKLS0tIFlSRGtYVS90LzJSZmJueDdReTFZ
            TGFmSkVyaHlZd3gzWjgzcXVpcm1uTHcKQp4MvE1v7pl36MEIeTowhw9ZtgqGvpUJ
            rhI8M5bCYmusXjiYKAcfhz12OnBd+QhXKFWeW3dDSpTkCBKBuOUyaw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14k8hl446lvn93q8mqam94fl46c5r6xzu7fcu0dq3763vp2wrze5slp2fkg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-14T11:32:11Z"
    mac: ENC[AES256_GCM,data:XjEUEJ/8sMRqrpsaQQ2g+KevDZAsRXPf4MuR1UovvQzxPy4hE7Z3lA+jeV/rpo30WHadqaK1FP0lZffJUnUHDvlG+JdIJGcQikuMO8sS4PnLzK04BL4bdncB6Ut1Ug0dSAyMD1BM5dF4YCwRXOKryKJtuxmpI36+SLFtGpRVOzY=,iv:dvyllbpLs09p2rbEfpxALZvcy6gChNsgg13zQD44nS4=,tag:4FRf0D6wsbMGOlitiCwb3Q==,type:str]
    version: 3.13.3
