apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/brk3/habits//deploy/kustomize/base?ref=v0.7.2
  - httproute.yaml
  - vpa.yaml

images:
  - name: ghcr.io/brk3/habits
    newTag: v0.7.2
  - name: ghcr.io/brk3/habits-frontend
    newTag: v0.7.2
