apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/brk3/habits//deploy/kustomize/base?ref=v0.6.1-alpha
  - httproute.yaml

images:
  - name: ghcr.io/brk3/habits
    newTag: v0.6.1-alpha
  - name: ghcr.io/brk3/habits-frontend
    newTag: v0.6.1-alpha
