apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  namespace: media
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: plex
          image: lscr.io/linuxserver/plex:latest
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Etc/UTC"
            - name: VERSION
              value: "docker"
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              memory: 4Gi
          volumeMounts:
            - name: config
              mountPath: /config
            - name: media
              mountPath: /data
            - name: dri
              mountPath: /dev/dri
      volumes:
        - name: config
          hostPath:
            path: /mnt/k3s-data/appdata/plex
            type: Directory
        - name: media
          hostPath:
            path: /mnt/media
            type: Directory
        - name: dri
          hostPath:
            path: /dev/dri
            type: Directory
