apiVersion: v1
kind: Secret
metadata:
    name: gluetun-credentials
    namespace: media
type: Opaque
stringData:
    VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:Pv0y5tnK,iv:w3ZZ5meWLJ/XL2+ABTG1WiFtyNCbEYQvapsrQtWpzwM=,tag:CutBL3FP/4mIyr0ROjeuHg==,type:str]
    VPN_TYPE: ENC[AES256_GCM,data:fMfbnW5JoiHC,iv:nCJMHeVGKxIV+Y80Hi96JfTNROFo6o473kGP7+fbXHI=,tag:LUjYuHTt9YzfmeDk9Kn3tg==,type:str]
    VPN_ENDPOINT_IP: ENC[AES256_GCM,data:Q48IU7k8glhNS8gpOg==,iv:vuj0loU5FBX2QWHZwCLxOGp5o0r6nr6BCIuoVhzTEso=,tag:oPZ8Y6rT3yARKVJcqQ497A==,type:str]
    VPN_ENDPOINT_PORT: ENC[AES256_GCM,data:9g4vLtw=,iv:MROHdrcUGmhndhB7yyIBPLM3m2z7v3p5iz35djKILnA=,tag:SaYl6XAMrEXHERLlNRLo8g==,type:str]
    WIREGUARD_PUBLIC_KEY: ENC[AES256_GCM,data:S88khfvgdIqR06c6kFTMHss9qVGn32uJwR7x8CNnfMbnQlccTUrAzKdKgB0=,iv:m4cwg6FVXrzv0UP+Vi+MVjqrSjkHwRogRiARYh3j/dM=,tag:l/HP+Xtb2gaOZsyO0brksQ==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:JuheK+DAz/uGc/NCcUxIhZJgnjcmuitfy3+CMrAAbdOAVdMkIuwIHXACS04=,iv:bfaP09SbU/cPH8Up4VTEW7JmR3jTk9siAlW5qivRSng=,tag:/p5EO1Rrmb0En+yCu4JzIg==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:7YBPiY3DtC8GgzU=,iv:TiOxbL++uv29d/JKbLXsP3NfTwCLMlny+RqYiwcqXPY=,tag:wwsNUJ/Rjz8ExFtCYUCg+w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMbWtOTTdOUDhVYXVXU0Nw
            d3VJa3c0SGJ2Y1NuVGZVY1RlVkFGL3RuNGhrCnFlZ1I1UGpQVjVxNnlDbUxURStL
            QzBrTG9KamM1Sm02c3hSaEtmSElEb1UKLS0tIE1qejdldjBKdmZJV0d3YUlrR2VT
            VEtYSXU1ZHl4UFc0WmJDMFRDZ2hWRHMKlF3F1D/VkeledrjvKx3hPPR5NyaPMZ4d
            n5D1WevendG1+U5OJD5Bv/4DqjieiQMTTYWMWtQTeiJjYLGrs1nFpg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14k8hl446lvn93q8mqam94fl46c5r6xzu7fcu0dq3763vp2wrze5slp2fkg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-08T20:23:42Z"
    mac: ENC[AES256_GCM,data:xqNIwJOXKKd5CyoNSia/otlM9O/kOWbLLn+YuvfYxyU3Czk4oiGvJiRhKkTI8cBsOr5/IewPvbSyiH+63Hsp8+V+GF8XHLMjdIFCl8E8wPlpOiz5aL436m27FXuRF/H1/EasrhgfFLXEbdLIWr+JplUizmWmLQF+Jjzf9km2RkQ=,iv:X1KoxEjNeNrgP53IJOZryWMsNjSI+FCpjnPJ82F0hl0=,tag:0BRcDE3+gvS8hxwnV8kunA==,type:str]
    version: 3.13.3
