apiVersion: v1
kind: Secret
metadata:
    name: brigid-provider-credentials
    namespace: media
type: Opaque
stringData:
    SUBLIMINAL_PROVIDER_OPENSUBTITLESCOM_PASSWORD: ENC[AES256_GCM,data:abFMfnnu5fR9ZO/1Nw==,iv:CBGHzDms1tUDKPCAcy+Qz6iJU324xrtZwcc/cQeFfUE=,tag:U5iZk3HyaVnBRdcBhDy7Rw==,type:str]
    SUBLIMINAL_PROVIDER_OPENSUBTITLESCOM_USERNAME: ENC[AES256_GCM,data:xjuRpUGi8vf04yM=,iv:ZWUfzzmGoP6F9E6/6iPBykVIFAJmdf2wYAgrs7zFYPA=,tag:x4uHVyE27TU/YudrudkU/w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUdndGdG5KSWgwVVJYdXY2
            UUFaVzFxVE82OC80QW5melpveW5kbWNaczBBClJCTm82NWd1VC9XK1pRWGxQb2Vq
            MXFYME12Z00vM01KeXdvRnE5c0dZaUUKLS0tIFpneVhXcmYwWVhtRXVCYUNXTi83
            dENRd200R3JpdjIxR01HWVl1bjBpUVkKWMpPgt+lPCP5D2812wP5rJllPcZ+dQJQ
            N7jv/x48dmcsSiOxK/tszBzwurFnd2xKQInVT6OHbboxO2MG/gTXtg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14k8hl446lvn93q8mqam94fl46c5r6xzu7fcu0dq3763vp2wrze5slp2fkg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-14T11:25:29Z"
    mac: ENC[AES256_GCM,data:O2KIWJ3XuDVTsWHVweHMxjid+r0+gUpueUiAcEOn+HBrU6950K4ogC+UIHTIdCw7W3TAE6j8v2MWTmOPT5cPYKFo+nYtHcftFMpCpiR4e3PmcQlvKtOLxPxmTxZVgvIw1caimGMRksC9Aa1Q+iHHtLBRTW6xr+fW7SWagPIiBAc=,iv:KinAfxukfybD34GgDs/i62rCcLuCLuSC6xahXhmj5LA=,tag:xHPgruiwUgGeRff1kLUFgg==,type:str]
    version: 3.13.3
