apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: qbittorrent
  namespace: media
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: qbittorrent
  updatePolicy:
    updateMode: "Recreate"
  resourcePolicy:
    containerPolicies:
      - containerName: qbittorrent
        maxAllowed:
          memory: 1Gi
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: plex
  namespace: media
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: plex
  updatePolicy:
    updateMode: "Off"
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: ogma
  namespace: media
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ogma
  updatePolicy:
    updateMode: "Recreate"
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: brigid
  namespace: media
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: brigid
  updatePolicy:
    updateMode: "Recreate"
