apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: qbittorrent
  namespace: media
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: qbittorrent
  updatePolicy:
    updateMode: "InPlaceOrRecreate"
  resourcePolicy:
    containerPolicies:
      - containerName: qbittorrent
        maxAllowed:
          memory: 1Gi
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: plex
  namespace: media
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: plex
  updatePolicy:
    updateMode: "InPlaceOrRecreate"
  resourcePolicy:
    containerPolicies:
      - containerName: plex
        maxAllowed:
          memory: 4Gi
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: ogma
  namespace: media
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ogma
  updatePolicy:
    updateMode: "InPlaceOrRecreate"
  resourcePolicy:
    containerPolicies:
      - containerName: ogma
        maxAllowed:
          memory: 512Mi
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: brigid
  namespace: media
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: brigid
  updatePolicy:
    updateMode: "InPlaceOrRecreate"
  resourcePolicy:
    containerPolicies:
      - containerName: brigid
        maxAllowed:
          memory: 512Mi
