apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: smartctl-exporter
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-smartctl-exporter
      app.kubernetes.io/instance: monitoring-smartctl-exporter
  endpoints:
    - port: http
      path: /metrics
      interval: 60s
