apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: homepage
data:
  settings.yaml: |
    title: Dagda
    theme: dark
    color: slate
    headerStyle: clean

  widgets.yaml: |
    - greeting:
        text_size: xl
        text: "Dagda"
    - datetime:
        text_size: xl
        format:
          timeStyle: short
    - search:
        provider: duckduckgo
        target: _blank

  bookmarks.yaml: |
    []

  services.yaml: |
    - Media:
        - Plex:
            href: https://plex.aiectomy.xyz
            icon: plex.png
        - Sonarr:
            href: https://sonarr.aiectomy.xyz
            icon: sonarr.png
        - Radarr:
            href: https://radarr.aiectomy.xyz
            icon: radarr.png
        - Prowlarr:
            href: https://prowlarr.aiectomy.xyz
            icon: prowlarr.png
        - qBittorrent:
            href: https://qbittorrent.aiectomy.xyz
            icon: qbittorrent.png
