apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - rbac.yaml
  - deployment.yaml
  - httproute.yaml
configMapGenerator:
  - name: homepage-config
    namespace: homepage
    files:
      - config/settings.yaml
      - config/widgets.yaml
      - config/services.yaml
      - config/bookmarks.yaml
      - config/kubernetes.yaml
