apiVersion: v1
kind: ConfigMap
metadata:
  name: glance-config
  namespace: glance
data:
  glance.yml: |
    pages:
      - name: Home
        columns:
          - size: small
            widgets:
              - type: calendar
                first-day-of-week: monday

              - type: weather
                location: Dublin, Ireland
                units: metric
                hour-format: 24h

              - type: clock
                hour-format: 24h
                timezones:
                  - timezone: America/New_York
                    label: New York
                  - timezone: America/New_York
                    label: East US
                  - timezone: America/Los_Angeles
                    label: West US
                  - timezone: Asia/Kolkata
                    label: Hyderabad

          - size: full
            widgets:
              - type: monitor
                title: Homelab services
                cache: 1m
                sites:
                  - title: Forgejo
                    url: https://forgejo.aiectomy.xyz
                  - title: Habits
                    url: https://habits.aiectomy.xyz
                  - title: Plex
                    url: https://plex.aiectomy.xyz
                    check-url: https://plex.aiectomy.xyz/identity
                  - title: qBittorrent
                    url: https://qbittorrent.aiectomy.xyz

              - type: group
                widgets:
                  - type: hacker-news
                  - type: lobsters

          - size: small
            widgets:
              - type: custom-api
                title: Quote of the Day
                cache: 12h
                url: https://zenquotes.io/api/today
                template: |
                  <blockquote>
                    <p>&ldquo;{{ .JSON.String "0.q" }}&rdquo;</p>
                    <footer class="color-highlight">&mdash; {{ .JSON.String "0.a" }}</footer>
                  </blockquote>

              - type: releases
                cache: 1d
                repositories:
                  - glanceapp/glance
                  - fluxcd/flux2
                  - k3s-io/k3s
                  - envoyproxy/gateway
                  - cert-manager/cert-manager
