apiVersion: v1
kind: ConfigMap
metadata:
  name: glance-config
  namespace: glance
data:
  glance.yml: |
    pages:
      - name: Home
        columns:
          - size: small
            widgets:
              - type: calendar
                first-day-of-week: monday

              - type: weather
                location: Dublin, Ireland
                units: metric
                hour-format: 24h

              - type: clock
                hour-format: 24h
                timezones:
                  - timezone: America/New_York
                    label: New York
                  - timezone: America/New_York
                    label: East US
                  - timezone: America/Los_Angeles
                    label: West US
                  - timezone: Asia/Kolkata
                    label: Hyderabad

          - size: full
            widgets:
              - type: monitor
                title: Homelab services
                cache: 1m
                sites:
                  - title: Forgejo
                    url: https://forgejo.aiectomy.xyz
                  - title: Habits
                    url: https://habits.aiectomy.xyz
                  - title: Plex
                    url: https://plex.aiectomy.xyz
                    check-url: https://plex.aiectomy.xyz/identity
                  - title: qBittorrent
                    url: https://qbittorrent.aiectomy.xyz

              - type: group
                widgets:
                  - type: hacker-news
                  - type: lobsters

          - size: small
            widgets:
              - type: custom-api
                title: Quote of the Day
                cache: 12h
                url: https://zenquotes.io/api/today
                template: |
                  <blockquote>
                    <p>&ldquo;{{ .JSON.String "0.q" }}&rdquo;</p>
                    <footer class="color-highlight">&mdash; {{ .JSON.String "0.a" }}</footer>
                  </blockquote>

              - type: custom-api
                title: Infra versions
                cache: 12h
                subrequests:
                  glance:
                    url: https://api.github.com/repos/glanceapp/glance/releases/latest
                  flux2:
                    url: https://api.github.com/repos/fluxcd/flux2/releases/latest
                  k3s:
                    url: https://api.github.com/repos/k3s-io/k3s/releases/latest
                  envoy-gateway:
                    url: https://api.github.com/repos/envoyproxy/gateway/releases/latest
                  cert-manager:
                    url: https://api.github.com/repos/cert-manager/cert-manager/releases/latest
                template: |
                  <ul class="list list-gap-10">
                    {{ $current := "v0.8.5" }}
                    {{ $latest := (.Subrequest "glance").JSON.String "tag_name" }}
                    <li class="flex justify-between">
                      <span>Glance</span>
                      <a href="{{ (.Subrequest "glance").JSON.String "html_url" }}" target="_blank">
                        {{ if eq $current $latest }}{{ $current }}{{ else }}{{ $current }} &rarr; {{ $latest }}{{ end }}
                      </a>
                    </li>
                    {{ $current = "v2.9.4" }}
                    {{ $latest = (.Subrequest "flux2").JSON.String "tag_name" }}
                    <li class="flex justify-between">
                      <span>Flux</span>
                      <a href="{{ (.Subrequest "flux2").JSON.String "html_url" }}" target="_blank">
                        {{ if eq $current $latest }}{{ $current }}{{ else }}{{ $current }} &rarr; {{ $latest }}{{ end }}
                      </a>
                    </li>
                    {{ $current = "v1.36.3+k3s1" }}
                    {{ $latest = (.Subrequest "k3s").JSON.String "tag_name" }}
                    <li class="flex justify-between">
                      <span>k3s</span>
                      <a href="{{ (.Subrequest "k3s").JSON.String "html_url" }}" target="_blank">
                        {{ if eq $current $latest }}{{ $current }}{{ else }}{{ $current }} &rarr; {{ $latest }}{{ end }}
                      </a>
                    </li>
                    {{ $current = "v1.8.3" }}
                    {{ $latest = (.Subrequest "envoy-gateway").JSON.String "tag_name" }}
                    <li class="flex justify-between">
                      <span>Envoy Gateway</span>
                      <a href="{{ (.Subrequest "envoy-gateway").JSON.String "html_url" }}" target="_blank">
                        {{ if eq $current $latest }}{{ $current }}{{ else }}{{ $current }} &rarr; {{ $latest }}{{ end }}
                      </a>
                    </li>
                    {{ $current = "v1.21.1" }}
                    {{ $latest = (.Subrequest "cert-manager").JSON.String "tag_name" }}
                    <li class="flex justify-between">
                      <span>cert-manager</span>
                      <a href="{{ (.Subrequest "cert-manager").JSON.String "html_url" }}" target="_blank">
                        {{ if eq $current $latest }}{{ $current }}{{ else }}{{ $current }} &rarr; {{ $latest }}{{ end }}
                      </a>
                    </li>
                  </ul>
