apiVersion: v1
kind: Secret
metadata:
    name: glance-lastfm
    namespace: glance
type: Opaque
stringData:
    LASTFM_API_KEY: ENC[AES256_GCM,data:IkzgSWL+azte6fk3EoKdY/b9BdifhqjjZ27DZ1iuaFc=,iv:8A4ciraWAte/1gFc85WBQY0wRNm+tf7zXckE1oHvA9s=,tag:h3CJ9ayNteR9AYuuBghe3g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZNlAySjM5SGJ4azlWZmdR
            a0c0N2kvbmRlQkVrZ0xraUUydHprWm0yWDBBCnBvRDNCanF2K2VaajNMUS83TTFM
            N1V3WGJYSjc4WWN3WDU0UXFKSU5tUVkKLS0tIGhzVE82Qm52ZGlKT2ZLZzNMV0Jy
            azg2WVlNZjBMaGR5ZGd0cFZRajRyQlEKsKDOMXh2JKcKW+HzjK1Xpzbkxv6Tr26o
            NJ81tgTZpLN4rN8Ru4fS7u3ZfNk+gKM/ITd7ZO/B8Y5JJ8yAQ3PzeQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14k8hl446lvn93q8mqam94fl46c5r6xzu7fcu0dq3763vp2wrze5slp2fkg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-14T16:24:25Z"
    mac: ENC[AES256_GCM,data:L4i1naW9lPXpJn5hYnKU5+ynPE9hRM0wJnBikG7xU0DOd+1sHBZIGMzLZ5wmMvAlTZXsFWw302Lao01MVdk1vXsJMwJoPzSWWInNInJEPVO+x7RwzxIrFMxerCPdubxNZz37kP6lXpqlYMIgUI1vnXqq6KPCWr8AzGVNg6fKfqw=,iv:QOuJqBnQ0GxGrfh/rNObfJ4nUde3PtpEvqbsK3zuep4=,tag:k1iyDBRRgNGu/Xi/PiuolA==,type:str]
    version: 3.13.3
