apiVersion: v1
kind: Secret
metadata:
    name: glance-lastfm
    namespace: glance
type: Opaque
stringData:
    LASTFM_API_KEY: ENC[AES256_GCM,data:OEhOx753anm7PA==,iv:pp0ePkZgak5Z+Ht1bsR3UgiTnIy8auwcuTe+kf2SUBM=,tag:pMkw/uwEa4Rb/cyfHJ6ePA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOR2tlTERzVjFMQWE3N1lF
            MWYzRXFkYjMwK2dzYUpBQU0xelFlR1pScEU0Cm5CRlNuUzZnais2bmZCQ0VaTmRW
            clFQY2N6eEFuVjBQYWVLQ0NERmxlQUEKLS0tIDR6c1NCTm9udUtLb2hjcExrTzgv
            UUw3dW5aU0RMNzUzWUlTa29WSXBqMHcKEIuR36NuOzZ0RMKn7fY/9EvxmGuMbKjK
            BC2Jb2YfmYaQWEsinrHVPZDKaZtys1JwvHYWFHQb7Bfwcm8XL56Z3w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14k8hl446lvn93q8mqam94fl46c5r6xzu7fcu0dq3763vp2wrze5slp2fkg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-14T16:13:29Z"
    mac: ENC[AES256_GCM,data:c3muj7aI/Be0myT/81WjC4aOGoORNf++CSGY9YhapHjhK7oJa5qUlVtxqI7yX+bxV+anLn5orlKcIOu8a1D03B8zTsHs9gtrw8dCOKKjPUbVSX87eJLk8b0dAeDJuyVoLSMYz3iR+8HfbBJn51LztF/u9EEB0ff5efwLzK6OkmA=,iv:akuUwUvTrYNu7WsBfefRET43dKYBwiFXb2od4S61ogY=,tag:XHoMsnzKRdLg9O+JtP/O3g==,type:str]
    version: 3.13.3
