apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: ogma
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: ogma
  digestReflectionPolicy: IfNotPresent
  policy:
    semver:
      range: ">=0.1.0"
