apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - imagerepository-qbittorrent.yaml
  - imagepolicy-qbittorrent.yaml
  - imagerepository-ogma.yaml
  - imagepolicy-ogma.yaml
  - imagerepository-plex.yaml
  - imagepolicy-plex.yaml
  - imagerepository-brigid.yaml
  - imagepolicy-brigid.yaml
  - imagerepository-forgejo.yaml
  - imagepolicy-forgejo.yaml
  - imagerepository-forgejo-runner.yaml
  - imagepolicy-forgejo-runner.yaml
  - imagerepository-glance.yaml
  - imagepolicy-glance.yaml
  - imagerepository-movieswipe.yaml
  - imagepolicy-movieswipe.yaml
  - imagerepository-habits.yaml
  - imagepolicy-habits.yaml
  - imagerepository-habits-frontend.yaml
  - imagepolicy-habits-frontend.yaml
  - imageupdateautomation.yaml
