apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:BSrcvjJJx46q7Vsn+7skXbIZBIFh+waAB0cRGhSpflz2X0pKW2tlfqAsNO1jmv255ea1AZI=,iv:xpiH4k+a3mHV5NPlyvaRRzAE0FDtza+wFLnUI6su/Qo=,tag:cC9r+RMmZeBnW7XzNsDqtg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzNk1KSHJKcDk5dnVHUFZx
            NlBQQ2xYeStDU0o0alQ5UTRKQnNMS3dWcVhzCkNmN2owOTIwcS8yc3lyZ20rdDNr
            RjV2V2ZGNUt6aFdpR0l3OGRzK09FelkKLS0tIFQxMG55WVgyWlc1ZTlHZjJ2VGJz
            dCsrTm02LzFUOW4zMlBPWmNGaEVpMTgKADhXWixEXoXjXrI/K8z5VEV0vnepEuZM
            8HYDXjGkTZAE+vLcF8UP7n6Lc576NsZ+DlREJuaJRTw1XSBrhaDmLg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14k8hl446lvn93q8mqam94fl46c5r6xzu7fcu0dq3763vp2wrze5slp2fkg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-14T11:32:11Z"
    mac: ENC[AES256_GCM,data:RfdJFPD95qQn4rNb2XllREtwtGNQo7MJJnASyLo5xuRLEqvyYSI+TBQaOzwk6vHdadi2lU7TUH9NEajsoBIHkriMfw7XniUfFAE1Ft9Idp9BqL0kD1fysl2ESpkuIp9cwbLKgR1M/TLUdAyfjI73oW22Frili2xRAl1ChKks9lQ=,iv:g/lGVksSk985ttLRTK45LgfKsUKWRNTQhYGqTszqdJ4=,tag:+HroFsD7MT6DLU/MpjuH2g==,type:str]
    version: 3.13.3
