apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
    namespace: tailscale
type: Opaque
stringData:
    client_id: ENC[AES256_GCM,data:mN7qI/pH9/IR0Q==,iv:jYR+q4l6xauo40F+OvSnhvvN7WthGoyWRr2eY7tHVXI=,tag:SLi47S5vO0dsNmkRedDj/g==,type:str]
    client_secret: ENC[AES256_GCM,data:NViro8DgRaLniQ==,iv:++sXCI47nHcJI2F6StLd0PCQAIETXbVetw+OF98FcGE=,tag:4UTqK6WbZBQ1qMgW11AGFw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwZUV2K3l0YnpuN1B6bCtD
            Qk4wb1VDV29XSm9BNXpOeFBTLzFiODdmZ25nClMxRWxhN0xJWkNRRUtmTUZUWjdk
            L2dScUFVWlNBdlN0TG0wdnZSc0NwNk0KLS0tIDRVNitPenk5ZmYrRVpZZFVCdmMx
            S0lOSzNkaG44cnF5L1gycHYxL0VGalEKbxSX8lvxlgHxk3CL4KbXGV4PjjZWzv5X
            9agNPN5vlDjb+hafseqzGKN9ihjZpMVKp/3Pa35aecJ+hClCuU2yJQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14k8hl446lvn93q8mqam94fl46c5r6xzu7fcu0dq3763vp2wrze5slp2fkg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-14T16:52:22Z"
    mac: ENC[AES256_GCM,data:3T9sNGgfhQpy5fA5z9kMG+RwvrGlubd/wgBQL6ZH5hQdRO12L4RUuYDgmb0tVow34utxx7se0vxqsTGH6dD2K85fEEUrryKynV6ucEJR9GPAOIhTVUCaYAnDAMlDXv0sJgfSFBnUZI/pL6THRJP88lGlmhiC7kW5iGccnXeEIe4=,iv:QTJduuBjSH1oEXajlt8qgyC24Yptja+uZT64LjIWyKQ=,tag:5tlo4dIVsYYVivMbYb2ZfA==,type:str]
    version: 3.13.3
