apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
    namespace: tailscale
type: Opaque
stringData:
    client_id: ENC[AES256_GCM,data:VJJVTyrzRT6Wz+WNrT1xRMA=,iv:kLwQaN6E9Vdf9usEXfL/Ng7l9DowFWtiNvTP+ngkOt0=,tag:ZVkrU5vepOevNrzZcU1hcA==,type:str]
    client_secret: ENC[AES256_GCM,data:QntpBrF0Dz4Fd4/u+m9y+kcvFKN5NRn478O+ep1YlvWWBQ/etum2s7POtkRBAPGZ8eb4wzRA08/4er1w3QoTpw==,iv:LaopjnHiVLap52FIVApbF7fnqBWeC9vdsrfd4jLtyng=,tag:4c5bDdws3k0e2rfFtTmVKA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1Ti9ld1RTUVpFK2hhTEhZ
            ZzRhTjh4Y0g3WEYvVldTc3laUnhBMlVqOVd3Ck9TOFV3eFZIblRrdFVZZklhNjVl
            Y2sxMzRhQ3IzRERGU2RkMm84TXM2amcKLS0tIDdCQjMvU25WT2pmVGN2RmtJM1pm
            S0hjdWZqS1dYOFpYWU9jaGtaMDdzaTAKQfp2sf+zAsv71RsodqK9KQbXuaGFi/PV
            6Tim26ZOCLTfowD4WWeZAWeTSFvvUn9UtnFOrdPWMUAvnCG1logLtw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14k8hl446lvn93q8mqam94fl46c5r6xzu7fcu0dq3763vp2wrze5slp2fkg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-17T22:27:51Z"
    mac: ENC[AES256_GCM,data:CxRD3pPR+h/uJ/yfTcmr1QBuOd7A9X+o27R1CFbAGVufelU/viESYEDnrXYr1RkVpWG/ylhMfLga/MxYj+NhSIJeMX+FDtQPgbmhH8R4SNeHu3AZT2F33KheUs6e8sEivmmELypZPDkA7BxjMMKH7OSby5ZiEV0gINXmyHUN904=,iv:+7Za81ACIfvo1iTS2hC+odZznqp2aZKmIrtJpnJj7ZA=,tag:kWbKtlDhr3/MopxBeWf6IQ==,type:str]
    version: 3.13.3
